name: Generate Pac-Man Game

on:
  schedule: # Executa automaticamente a cada 24 horas
    - cron: "0 */24 * * *"
  workflow_dispatch: # Permite disparo manual
  push: # Executa em cada push para a branch principal
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Faz o push do SVG gerado para a branch de saída
      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
